from snakemake.utils import min_version
import sys


min_version("9.0.0")

shell.prefix("set -euo pipefail")


report: "report/workflow.rst"


##### Target rules #####


include: "rules/init.smk"
include: "rules/cuttlefish.smk"
include: "rules/tree.smk"
include: "rules/mincuts.smk"
include: "rules/sqldb.smk"
include: "rules/pcdbg.smk"
include: "rules/bubblegun.smk"
include: "rules/colored_deletions.smk"
include: "rules/breakpoints.smk"
include: "rules/coherence.smk"
include: "rules/stratification.smk"


PRODUCE_COLORED_DELETIONS = config.get("produce_colored_deletions", True)
PRODUCE_BREAKPOINTS = config.get("produce_breakpoints", False)
PRODUCE_PERSISTENCE = config.get("produce_persistence",
                                  config.get("produce_coherence_decay", False))
PRODUCE_STRATIFICATION = config.get("produce_stratification", False)

pcdbg_targets = expand(fn_pcdbg(_batch="{batch}"), batch=get_batches())
compression_targets = expand(
    fn_compression_metrics(_batch="{batch}"), batch=get_batches()
)
deletion_targets = (
    expand(fn_deletionbubbles(_batch="{batch}"), batch=get_batches())
    if PRODUCE_COLORED_DELETIONS
    else []
)
breakpoint_targets = (
    expand(fn_breakpoints(_batch="{batch}"), batch=get_batches())
    + expand(fn_breakpoint_summary(_batch="{batch}"), batch=get_batches())
    + expand(fn_boundary_severity(_batch="{batch}"), batch=get_batches())
    + expand(fn_boundary_severity_plot(_batch="{batch}"), batch=get_batches())
    if PRODUCE_BREAKPOINTS
    else []
)
persistence_targets = (
    expand(fn_evolutionary_persistence(_batch="{batch}"), batch=get_batches())
    + expand(fn_evolutionary_persistence_plot(_batch="{batch}"), batch=get_batches())
    if PRODUCE_PERSISTENCE
    else []
)
stratification_targets = (
    expand(fn_evolutionary_stratification(_batch="{batch}"), batch=get_batches())
    + expand(fn_evolutionary_stratification_plot(_batch="{batch}"), batch=get_batches())
    if PRODUCE_STRATIFICATION
    else []
)


## WILDCARDS CONSTRAINS
wildcard_constraints:
    sample=r"[a-zA-Z0-9_-]+",
    batch=r"[a-zA-Z0-9_-]+",


rule all:
    input:
        pcdbg_targets + compression_targets + deletion_targets + breakpoint_targets + persistence_targets + stratification_targets,
