from snakemake.utils import min_version
import sys


min_version("9.0.0")

shell.prefix("set -euo pipefail")


report: "report/workflow.rst"


##### Target rules #####


include: "rules/init.smk"
include: "rules/cuttlefish.smk"
include: "rules/tree.smk"
include: "rules/mincuts.smk"
include: "rules/sqldb.smk"
include: "rules/pcdbg.smk"
include: "rules/bubblegun.smk"
include: "rules/colored_deletions.smk"
include: "rules/breakpoints.smk"
include: "rules/coherence.smk"


PRODUCE_COLORED_DELETIONS = config.get("produce_colored_deletions", True)
PRODUCE_BREAKPOINTS = config.get("produce_breakpoints", False)
PRODUCE_COHERENCE_DECAY = config.get("produce_coherence_decay", False)

pcdbg_targets = expand(fn_pcdbg(_batch="{batch}"), batch=get_batches())
compression_targets = expand(
    fn_compression_metrics(_batch="{batch}"), batch=get_batches()
)
deletion_targets = (
    expand(fn_deletionbubbles(_batch="{batch}"), batch=get_batches())
    if PRODUCE_COLORED_DELETIONS
    else []
)
breakpoint_targets = (
    expand(fn_breakpoints(_batch="{batch}"), batch=get_batches())
    + expand(fn_breakpoint_summary(_batch="{batch}"), batch=get_batches())
    + expand(fn_breakpoints_stratified(_batch="{batch}"), batch=get_batches())
    if PRODUCE_BREAKPOINTS
    else []
)
coherence_targets = (
    expand(fn_coherence_decay(_batch="{batch}"), batch=get_batches())
    + expand(fn_coherence_decay_plot(_batch="{batch}"), batch=get_batches())
    if PRODUCE_COHERENCE_DECAY
    else []
)


## WILDCARDS CONSTRAINS
wildcard_constraints:
    sample=r"[a-zA-Z0-9_-]+",
    batch=r"[a-zA-Z0-9_-]+",


rule all:
    input:
        pcdbg_targets + compression_targets + deletion_targets + breakpoint_targets + coherence_targets,
