########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow
input_dir:            input
intermediate_dir:     intermediate
output_dir:           output
conda_dir:            .conda

# (2) Parameters for Snakemake execution
use_conda:            True # build conda environments automatically by Snakemake

##############
# PARAMETERS #
##############

# (1) General parameters; notes:
#     - kmer length defines k for dBGs 
#     - if trees_required is true, then workflow requires trees
#     - max_colors is the max number of hexadecimal color codes to include in the dbg for vis
#     - tmp_dir is the path to a temp directory on your system.  
kmer_length:          31
trees_required:       False
max_colors:           70
tmp_dir:              /tmp
produce_colored_deletions: False
produce_breakpoints: True
  

# (2) Threading; notes:
#     - controls max threads for multithreaded steps
threads:              8

# (3) Mashtree/attotree parameters; notes:
#     - sketch size should be at least 10k to achieve a sufficient resolution
mashtree_kmer_length: 21
mashtree_sketch_size: 10000

# (4) Parsimony parameters
parsimony:
  mode: fitch                # fitch | sankoff
  sankoff_branch_penalty:    null   # overrides auto-scaling penalty when set
