########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow
input_dir:            input
intermediate_dir:     intermediate
output_dir:           output
conda_dir:            .conda

# (2) Parameters for Snakemake execution
use_conda:            True # build conda environments automatically by Snakemake

##############
# PARAMETERS #
##############

# (1) General parameters; notes:
#     - kmer length defines k for dBGs 
#     - if trees_required is true, then the workflow will insist on user-provided trees
#     - max_colors is the number of hexadecimal color codes to include in the dbg
kmer_length:          21
trees_required:       False
max_colors:           70
tmp_dir:              .tmp
produce_colored_deletions: True
produce_breakpoints: True
produce_coherence_decay: True
produce_minimalcuts_colors: True
  

# (2) Threading; notes:
#     - controls max threads for parallelizable rules (cuttlefish, parsimony, etc.)
#     - set conservatively on shared servers with HDDs to avoid I/O overload
threads:              4

# (3) Mashtree/attotree parameters; notes:
#     - sketch size should be at least 10k to achieve a sufficient resolution
mashtree_kmer_length: 21
mashtree_sketch_size: 10000
  
# (3) Parsimony parameters
parsimony:
  mode: fitch                # fitch | sankoff
  sankoff_branch_penalty:    null   # overrides auto-scaling penalty when set
