#!/usr/bin/env python3

import colorcet as cc
from loguru import logger
import argparse
import os
import sys
from sql_utils import lookup_unitigs_batch
import sqlite3


def process_cuts_and_generate_palette(cutsperunitig, max_colors):
    cut_countdict = {}

    logger.info("Counting cuts...")
    with open(cutsperunitig, "r") as file:
        for line in file:
            parts = line.strip().split("\t")
            if " OR " in parts[1]:
                both_soln = parts[1].split(" OR ")
                values = ",".join(sorted(both_soln[0].split(",")))
            else:
                values = ",".join(sorted(parts[1].split(",")))
            if values != "Root":
                cut_countdict[values] = cut_countdict.get(values, 0) + 1

    logger.debug(cut_countdict)
    logger.info("Generating color palette...")
    palette = cc.glasbey[:max_colors]
    most_common_cuts = sorted(cut_countdict.items(),
                              key=lambda x: x[1],
                              reverse=True)[:max_colors]
    most_common_cuts_list = [key for key, _ in most_common_cuts]
    cut_to_colors = {
        cuts: palette[i]
        for i, cuts in enumerate(most_common_cuts_list)
    }
    cut_to_colors['Root'] = "#000000"
    logger.debug(cut_to_colors)

    return cut_to_colors


def modify_gfa_with_colors(gfa_filename, sqldb, cut_colors, outpath):
    db = sqlite3.connect(sqldb)
    line_count = 0
    logger.info(f"Generating new GFA file...")

    # Process the GFA file
    # Write the modified GFA to a new file
    os.makedirs(os.path.dirname(outpath), exist_ok=True)
    with open(outpath, "w") as out_file:
        with open(gfa_filename, "r") as gfa_file:
            for line in gfa_file:
                if line.startswith("S"):
                    parts = line.split()
                    segment_id = parts[1]
                    logger.debug(f"Parsing {segment_id}")
                    cutstring = lookup_unitigs_batch(
                        db, [segment_id],
                        output_neighbors=False)[segment_id]['colors']
                    logger.debug(f"Cutstring to parse: {cutstring}")
                    if " OR " in cutstring:
                        both_soln = cutstring.split(" OR ")
                        logger.warning(
                            f"Multiple solutions for {segment_id}. Only coloring by first solution"
                        )
                        cuts = ",".join(sorted(both_soln[0].split(",")))
                    else:
                        cuts = ",".join(sorted(cutstring.split(",")))
                    logger.debug(f"Cutstring parsed to {cuts}")
                    color = cut_colors.get(cuts, "#808080")
                    logger.debug(f"Corresponding color: {color}")
                    out_file.writelines(line.strip() +
                                        f"\tCB:Z:{color}\tLB:Z:{cutstring}\n")
                elif line.startswith("P"):
                    continue
                else:
                    out_file.writelines(line)
                line_count += 1
                if line_count % 1000000 == 0:
                    logger.debug(f"Processed {line_count} lines.")
    logger.debug(f"Finished processing. Total lines processed: {line_count}")
    logger.info(f"Finished writing to {outpath}")
    db.close()


def main():
    parser = argparse.ArgumentParser(
        description="Add color information and cuts to the GFA file specified")
    parser.add_argument("-m",
                        "--mincuts",
                        type=str,
                        help="Path to minimal cuts per unitig file")
    parser.add_argument("-d", "--sqldb", type=str, help="Path to SQL db")
    parser.add_argument("-g", "--gfa", type=str, help="Path to GFA input file")
    parser.add_argument("-o",
                        "--output",
                        type=str,
                        help="Path to the output gfa file for BandageNG")
    parser.add_argument(
        "-mc",
        "--max_colors",
        type=int,
        default=20,
        help="How many colors to visualize. Max is 70, default is 20.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help=
        "Increase verbosity level. Can be specified multiple times for more detailed logs.",
    )

    args = parser.parse_args()

    if args.verbose == 0:
        logger.remove()
    elif args.verbose == 1:
        logger.remove()
        logger.add(sys.stderr, level="INFO")
    elif args.verbose >= 2:
        logger.remove()
        logger.add(sys.stderr, level="DEBUG")

    cut_to_colors = process_cuts_and_generate_palette(args.mincuts,
                                                      args.max_colors)
    logger.info("Color palette generated")
    modify_gfa_with_colors(args.gfa, args.sqldb, cut_to_colors, args.output)


# Main Execution
if __name__ == "__main__":
    main()
