#!/usr/bin/env python3

import pandas as pd
import sys
from loguru import logger
from collections import defaultdict

gfa1 = sys.argv[1]
fof = sys.argv[2]
output = sys.argv[3]

# Step 1: Read file of files
with open(fof, "r") as f:
    idx_to_filepath = {index: line.strip() for index, line in enumerate(f)}

logger.debug("Read in {} files", len(idx_to_filepath))

# Initialize a dictionary using defaultdict
data_dict = defaultdict(set)

# Set to store all unique unitigs
all_unitigs = set()

# Read GFA file and gather unitigs for each sample
with open(gfa1, "r") as file:
    for line in file:
        parts = line.strip().split()
        if parts[0] == "P":
            ref_seq_idx = parts[1].split("_")[0].split(":")[1]
            ref_seq = idx_to_filepath[int(ref_seq_idx) - 1]
            unitigs = set(parts[2].replace("+", "").replace("-",
                                                            "").split(","))
            data_dict[ref_seq].update(unitigs)
            all_unitigs.update(unitigs)

logger.debug("Read in {} unitigs", len(all_unitigs))

# Create a DataFrame with all zeros
df = pd.DataFrame(0, index=list(all_unitigs), columns=idx_to_filepath.values())

logger.debug("Created empty unitig matrix!")

# Update DataFrame with 1 where unitigs exist
for sample, unitigs in data_dict.items():
    df.loc[list(unitigs), sample] = 1

logger.debug("Updated unitig matrix with present unitigs!")

# Transpose and output the DataFrame
df.to_csv(output, sep="\t")

logger.debug("Outputted to {}", output)
