import os
import sys
import glob
import argparse

# ╭───────────────────────────────────────────────────────────────────────────╮
#   SETUP
# ╰───────────────────────────────────────────────────────────────────────────╯

datasets = set(["mtbc-highquality", "chlamydia-661k"])

# Assigning obtained values
DATASET_CHOSEN = config["DATA"]
if DATASET_CHOSEN not in datasets:
    print(f"Dataset chosen is not available from the options: {DATASET_CHOSEN}")
    sys.exit(2)
MAIN_DIR = os.path.join(
    os.getcwd(), "data", DATASET_CHOSEN, "phylogeny-colored-dbgs--spectrum"
)
os.makedirs(MAIN_DIR, exist_ok=True)
KMERSIZE = config["KMER"]


def main_dir(child):
    return os.path.join(MAIN_DIR, child)


sample_paths = glob.glob(f"{MAIN_DIR}/assemblies/*")
sample_files = [os.path.basename(acc) for acc in sample_paths]
samples = [x.split(".fa")[0] for x in sample_files]

# -----------------------------------------------------------------------------


# ╭───────────────────────────────────────────────────────────────────────────╮
#   RULES
# ╰───────────────────────────────────────────────────────────────────────────╯
#
# RULE ALL
# -----------------------------------------------------------------------------
rule all:
    input:
        filtered_bubbles=main_dir(f"bubbles/filteredbubbles"),
        phylogenycdbg=main_dir(
            f"colored-debruijngraph-gfa1/phylogenycolored_dbg_k{KMERSIZE}.gfa"
        ),
        bubblepaths_outputted=main_dir(f"bubbles/filtered_bubbles_output"),


# RULE: Make classic colored, compacted de bruijn graph using Cuttlefish
# -----------------------------------------------------------------------------
rule run_cuttlefish_gfa1:
    output:
        gfa1=main_dir(
            f"colored-debruijngraph-gfa1/colored_dbg_k{KMERSIZE}_cuttlefish.gfa1"
        ),
        json=main_dir(
            f"colored-debruijngraph-gfa1/colored_dbg_k{KMERSIZE}_cuttlefish.json"
        ),
        fof=main_dir("colored-debruijngraph-gfa1/list_of_files.txt"),
    params:
        kmersize=KMERSIZE,
        tempdir="/n/scratch3/users/a/ak586/cuttlefish/tmp",
    conda:
        "./envs/cuttlefish.yml"
    threads: 32
    resources:
        mem_gb=50,
        partition="medium",
        time="4-00:00",
    shell:
        """
        ulimit -n 2048
        rm -r {params.tempdir}
        mkdir -p {params.tempdir}
        OUTPUTDIR=$(dirname {output.gfa1})
        mkdir -p $OUTPUTDIR
        find $OUTPUTDIR/../../assemblies/ -type f > $OUTPUTDIR/list_of_files.txt
        cuttlefish build \
                -l $OUTPUTDIR/list_of_files.txt \
                -t {threads} \
                -k {params.kmersize} \
                -f 1 \
                -m 50 \
                -w {params.tempdir} \
                -o $OUTPUTDIR/colored_dbg_k{params.kmersize}_cuttlefish
        """


# RULE: Generate unitig by sample matrix
# -----------------------------------------------------------------------------
rule unitig_sample_matrix_gfa1:
    input:
        gfa1=main_dir(
            f"colored-debruijngraph-gfa1/colored_dbg_k{KMERSIZE}_cuttlefish.gfa1"
        ),
        fof=main_dir("colored-debruijngraph-gfa1/list_of_files.txt"),
    output:
        binarymatrix=main_dir("unitig_sample_matrix/unitigs.colors.tsv"),
    conda:
        "./envs/pandas.yml"
    resources:
        time="0-10:00",
        mem_gb=30,
    shell:
        """
        ./scripts/generate_unitig_colormatrix_cuttlefish_gfa1 \
            {input.gfa1} \
            {input.fof} \
            {output}
        """


# RULE: Identify redundant color vectors and merge them
# -----------------------------------------------------------------------------
rule mergeredundantcolors:
    input:
        binarymatrix=main_dir("unitig_sample_matrix/unitigs.colors.tsv"),
    output:
        uniquecolors=main_dir("unitig_sample_matrix/uniquecolors.tsv"),
        redundantcolors=main_dir("unitig_sample_matrix/redundantcolors.csv"),
    conda:
        "./envs/pandas.yml"
    resources:
        time="0-01:00",
        mem_gb=50,
    shell:
        """
        ./scripts/uniquecolorvectors_from_colormatrix \
                {input} \
                {output.uniquecolors} \
                {output.redundantcolors}
        """


# RULE: Identify minimal cuts for each color possibility observed
# -----------------------------------------------------------------------------
rule minimal_cuts_percolorset:
    input:
        tree=main_dir("trees/sample_phylogeny.nwk"),
        uniquecolors=main_dir("unitig_sample_matrix/uniquecolors.tsv"),
    output:
        cuts=main_dir("minimal_cuts_output/minimal_cuts"),
    params:
        plotdir=main_dir("minimal_cuts_output/plots"),
        chunksize=5000,
    conda:
        "./envs/ete4.yml"
    resources:
        partition="medium",
        time="2-00:00",
        mem_gb=50,
    threads: 12
    shell:
        """
        mkdir -p $(dirname {output}) 
        mkdir -p {params.plotdir}
        ./scripts/minimal_cuts \
                {input.tree} \
                {input.uniquecolors} \
                -o {output} \
                -v --all \
                -j {threads} \
                -cs {params.chunksize}
        """


# RULE: Decompose cuts for each color. End result is a unitig on each line
## and the minimal cuts required to extract the samples that unitig is present
## in
# -----------------------------------------------------------------------------
rule decompose_redundant_colors:
    input:
        cuts=main_dir("minimal_cuts_output/minimal_cuts"),
        redundantcolors=main_dir("unitig_sample_matrix/redundantcolors.csv"),
    output:
        unitigs_to_cuts=main_dir("minimal_cuts_output/unitig_to_cuts"),
    conda:
        "./envs/pandas.yml"
    resources:
        time="0-01:00",
        mem_gb=30,
    shell:
        """
        ./scripts/map_unitigs-to-cuts {input.redundantcolors} {input.cuts} {output}
        """


# RULE: Build SQL db from minimal cuts soln + the dbg
# -----------------------------------------------------------------------------
rule build_sqldb:
    input:
        gfa1=main_dir(
            f"colored-debruijngraph-gfa1/colored_dbg_k{KMERSIZE}_cuttlefish.gfa1"
        ),
        cuts=main_dir("minimal_cuts_output/minimal_cuts"),
    output:
        sql=main_dir(f"colored-debruijngraph-gfa1/sql_k{KMERSIZE}.db"),
    conda:
        "./envs/pandas.yml"
    threads: 1
    resources:
        mem_gb=50,
        partition="small",
        time="3-00:00",
    shell:
        """
        ./scripts/gfa_to_sql \
                -g {input.gfa1} \
                -s {input.cuts} \
                -o {output.sql} \
                -vv 
        """


# RULE: Add color information to the GFA corresponding to the phylogeny
## info
# -----------------------------------------------------------------------------
rule add_colorinfo_to_gfa:
    input:
        gfa1=main_dir(
            f"colored-debruijngraph-gfa1/colored_dbg_k{KMERSIZE}_cuttlefish.gfa1"
        ),
        unitigs_to_cuts=main_dir("minimal_cuts_output/unitig_to_cuts"),
        sql=main_dir(f"colored-debruijngraph-gfa1/sql_k{KMERSIZE}.db"),
    output:
        main_dir(f"colored-debruijngraph-gfa1/phylogenycolored_dbg_k{KMERSIZE}.gfa"),
    resources:
        time="0-02:00",
    params:
        maxcolors=70,
    conda:
        "./envs/pandas.yml"
    shell:
        """
        ./scripts/add_coloredgfatag_cuttlefish-gfa1 \
                -g {input.gfa1} \
                -m {input.unitigs_to_cuts} \
                -d {input.sql}
                -o {output} \
                -vv \
                -mc {params.maxcolors}
        """


# RULE: Run BubbleGun to identify simple bubbles and superbubbles
# -----------------------------------------------------------------------------


rule run_bubblegun:
    input:
        gfa1=main_dir(
            f"colored-debruijngraph-gfa1/colored_dbg_k{KMERSIZE}_cuttlefish.gfa1"
        ),
    output:
        bubblejson=main_dir(f"bubbles/k{KMERSIZE}_bubbles.json"),
        bubblefasta=main_dir(f"bubbles/k{KMERSIZE}_bubbles.fasta"),
    resources:
        mem_gb=50,
        time="0-03:00",
    conda:
        "./envs/bubblegun.yml"
    shell:
        """
        mkdir -p $(dirname {output})
        BubbleGun -g {input.gfa1} \
                --log_file $(dirname {output.bubblejson})/log.log \
                bchains \
                --bubble_json {output.bubblejson} \
                --fasta {output.bubblefasta}
        """


# RULE: Find deletions from bubbles
# -----------------------------------------------------------------------------
rule find_colored_deletions:
    input:
        bubblejson=main_dir(f"bubbles/k{KMERSIZE}_bubbles.json"),
        unitigs_to_cuts=main_dir("minimal_cuts_output/unitig_to_cuts"),
        gfa1=main_dir(
            f"colored-debruijngraph-gfa1/colored_dbg_k{KMERSIZE}_cuttlefish.gfa1"
        ),
        sql=main_dir(f"colored-debruijngraph-gfa1/sql_k{KMERSIZE}.db"),
    output:
        filtered_bubbles=main_dir(f"bubbles/filteredbubbles"),
    threads: 20
    params:
        maxpaths=100000,
        timeout=600,
    resources:
        time="4-00:00",
        partition="medium",
        mem_gb=100,
    conda:
        "./envs/pandas.yml"
    shell:
        """
        ./scripts/find_colored_deletions \
                -g {input.gfa1} \
                -b {input.bubblejson} \
                --db {input.sql} \
                -u {input.unitigs_to_cuts} \ 
                -o {output} \
                -vv \
                --maxpaths {params.maxpaths} \
                -to {params.timeout} 
        """


# CHECKPOINT: Output sequence paths for each valid path in the bubble
# -----------------------------------------------------------------------------
checkpoint find_paths_for_deletions:
    input:
        sql=main_dir(f"colored-debruijngraph-gfa1/sql_k{KMERSIZE}.db"),
        filtered_bubbles=main_dir(f"bubbles/filteredbubbles"),
    output:
        directory(main_dir("bubbles/filtered_bubbles_dir")),
    threads: 4
    params:
        kmer=KMERSIZE,
    resources:
        time="0-05:00",
        partition="short",
        mem_gb=20,
    conda:
        "./envs/pandas.yml"
    shell:
        """
        ./scripts/paths_to_seqs \
                -d {input.sql} \
                -k {params.kmer} \
                -b {input.filtered_bubbles} \
                -vv \
                -o {output}
        """


def check_aggregate_filtered_bubbles(wildcards):
    checkpoint_output = checkpoints.find_paths_for_deletions.get(**wildcards).output[0]
    return expand(
        main_dir("bubbles/filtered_bubbles_dir/{i}.fasta"),
        i=glob_wildcards(os.path.join(checkpoint_output, "{i}.fasta")).i,
    )


rule aggregate_filtered_bubbles:
    input:
        check_aggregate_filtered_bubbles,
    resources:
        time="0-00:10",
        partition="short",
        mem_gb=1,
    output:
        main_dir(f"bubbles/filtered_bubbles_output"),


rule weight_phylogeny_by_cuts:
    input:
        unitig_to_cuts=main_dir("minimal_cuts_output/unitig_to_cuts"),
        tree=main_dir("trees/sample_phylogeny.nwk"),
        gfa1=main_dir(
            f"colored-debruijngraph-gfa1/colored_dbg_k{KMERSIZE}_cuttlefish.gfa1"
        ),
    output:
        weighted_tree=main_dir("trees/weighted_phylogeny.nwk"),
    conda:
        "./envs/ete4.yml"
    resources:
        time="0-03:00",
        mem_gb=30,
    shell:
        """
        ./scripts/weight_tree_bycuts {input.unitig_to_cuts} {input.tree} {input.gfa1} -o {output} -vv
        """


# RULE: Add cut info to GFA output [Needed for BandageNG visualization]
# -----------------------------------------------------------------------------
# RULE: Generate tree with mashtree if no tree supplied
# -----------------------------------------------------------------------------
# rule generate_tree:
#    output:
#        tree=main_dir("trees/sample_phylogeny.nwk"),
#    params:
#        genomedir=main_dir("../assemblies"),
#    output:
#        main_dir(
#            f"colored-debruijngraph-gfa1/phylogenycolored_dbg_k{KMERSIZE}_cuttlefish.gfa1"
#        ),
#    shell:
#        """
#        python ./scripts/add_coloredgfatag_cuttlefish.py {input.colormapping} {input.gfa1} {input.aligned_unitigs} {output}
#        """
#
#
# rule extract_all_unitigs:
#    input:
#        segfile=main_dir(
#            f"colored-debruijngraph/colored_dbg_k{KMERSIZE}_cuttlefish.cf_seg"
#        ),
#    output:
#        main_dir("colored-debruijngraph/unitigs.fa"),
#    shell:
#        """
#        awk '{{printf ">$s\\n%s\\n", $1, $2}}' {input} > {output}
#        """
#
#
# rule run_cuttlefish_reducedgfa:
#    output:
#        seqfile=main_dir(
#            f"colored-debruijngraph/colored_dbg_k{KMERSIZE}_cuttlefish.cf_seq"
#        ),
#        segfile=main_dir(
#            f"colored-debruijngraph/colored_dbg_k{KMERSIZE}_cuttlefish.cf_seg"
#        ),
#        json=main_dir(f"colored-debruijngraph/colored_dbg_k{KMERSIZE}_cuttlefish.json"),
#        fof=main_dir("colored-debruijngraph/list_of_files.txt"),
#    params:
#        kmersize=KMERSIZE,
#        tempdir="/n/scratch3/users/a/ak586/cuttlefish/tmp",
#    conda:
#        "./envs/cuttlefish.yml"
#    threads: 32
#    resources:
#        mem_gb=50,
#    shell:
#        """
#        ulimit -n 2048
#        mkdir -p {params.tempdir}
#        OUTPUTDIR=$(dirname {output.seqfile})
#        mkdir -p $OUTPUTDIR
#        find $OUTPUTDIR/../../assemblies/ -type f > $OUTPUTDIR/list_of_files.txt
#        cuttlefish build \
#                -l $OUTPUTDIR/list_of_files.txt \
#                -t {threads} \
#                -k {params.kmersize} \
#                -f 3 \
#                -m 50 \
#                -w {params.tempdir} \
#                -o $OUTPUTDIR/colored_dbg_k{params.kmersize}_cuttlefish
#        """
#
#
# rule unitig_sample_matrix_reducedgfa:
#    input:
#        seqfile=main_dir(
#            f"colored-debruijngraph/colored_dbg_k{KMERSIZE}_cuttlefish.cf_seq"
#        ),
#        segfile=main_dir(
#            f"colored-debruijngraph/colored_dbg_k{KMERSIZE}_cuttlefish.cf_seg"
#        ),
#        fof=main_dir(f"colored-debruijngraph/list_of_files.txt"),
#    output:
#        binarymatrix=main_dir("unitig_sample_matrix/unitigs.colors.tsv"),
#    conda:
#        "./envs/pandas.yml"
#    shell:
#        """
#        python ./scripts/generate_unitig_colormatrix_cuttlefish_gfareduced.py \
#                {input.segfile} \
#                {input.seqfile} \
#                {input.fof} \
#                {output}
#        """
#
#
## RULE: Add color information to GFA1 file for BandageNG visualization
## -----------------------------------------------------------------------------
#
#
# rule add_colorinfo_to_gfa1:
#    input:
#        gfa1=main_dir(
#            f"colored-debruijngraph-gfa1/colored_dbg_k{KMERSIZE}_cuttlefish.gfa1"
#        ),
#        colormapping=main_dir(f"trees/colormapping.tsv"),
#        aligned_unitigs=main_dir("prophyle/unitigs_mapped_to_prophyle.sam"),
#    output:
#        main_dir(
#            f"colored-debruijngraph-gfa1/phylogenycolored_dbg_k{KMERSIZE}_cuttlefish.gfa1"
#        ),
#    shell:
#        """
#        python ./scripts/add_coloredgfatag_cuttlefish.py {input.colormapping} {input.gfa1} {input.aligned_unitigs} {output}
#        """
